generator: admingenerator.generator.doctrine
params:
    i18n_catalog: YourTranslationDomain
    model: AppBundle\Entity\Item
    namespace_prefix: 
    concurrency_lock: ~
    bundle_name: AppBundle
    pk_requirement: ~
    fields: ~
    object_actions:
        delete: ~
    batch_actions:
        delete: ~
builders:
    list:
        params:
            title: List for AppBundle
            display: ~
            actions:
                new: ~
                excel: ~
            object_actions:
                edit: ~
                delete: ~
    excel:
        params: 
            export: 
               full:
                -       id
                -       title
                -       code
                -       guid
                -       note
               short:
                -       id
                -       code
                -       title
               simple:
                -       title


               # full:
               #    # credentials: 'hasRole("ROLE_ADMIN")'        
               #    icon:   fa-files-o 
               #    label:  Full report
               #    filename: ~
               #    filetype: ~
               #    datetime_format: ~
               #    fields: ~
               #    display: 
               #      - id
               #      - title
               #      - code
               #      - guid
               #      - note
               # short:
               #    # credentials: 'hasRole("ROLE_A")'        
               #    icon:   fa-file-excel-o
               #    label:  Short report
               #    display: 
               #      - id
               #      - code
               #      - title
               # simple:
               #    # credentials: 'hasRole("ROLE_B")'        
               #    icon:   fa-table
               #    label:  Simple report
               #    fields:
               #      fullName:
               #        label:  List of items
               #    display: 
               #      - title

    new:
        params:
            title: New object for AppBundle
            display: ~
            actions:
                save: ~
                list: ~
    edit:
        params:
            title: "You're editing the object \"%object%\"|{ %object%: Item.title }|"
            display: ~
            actions:
                save: ~
                list: ~
    show:
        params:
            title: "You're viewing the object \"%object%\"|{ %object%: Item.title }|"
            display: ~
            actions:
                list: ~
                new: ~
    actions:
        params:
            object_actions:
                delete: ~
            batch_actions:
                delete: ~
