generator: admingenerator.generator.doctrine
params:
    i18n_catalog: YourTranslationDomain
    model: AppBundle\Entity\Item
    namespace_prefix: 
    concurrency_lock: ~
    bundle_name: AppBundle
    pk_requirement: ~
    fields: ~
    object_actions:
        delete: ~
    batch_actions:
        delete: ~
builders:
    list:
        params:
            title: List for AppBundle
            display: ~
            actions:
                new: ~
                excel: ~
            object_actions:
                edit: ~
                delete: ~
    excel:
        params: 
            export:  
                full:
                    credentials:     'hasRole("ROLE_A")'        
                    show_button:     false
                    icon:            fa-files-o 
                    label:           Full report
                    filename:        full-report.xlsx
                    filetype:        Excel2007
                    datetime_format: Y-m-d H:i:s
                    display:
                        -            id
                        -            title
                        -            code
                        -            guid
                        -            note

                short:
                    credentials:     'hasRole("ROLE_B")'        
                    show_button:     true
                    icon:            fa-files-o 
                    label:           Show report
                    filename:        Short-repot.xls
                    filetype:        Excel5
                    datetime_format: d.m.Y
                    fields:          
                      title:
                        label:       Product name
                    display:
                        -            id
                        -            code
                        -            title

                simple:
                    -                title

    new:
        params:
            title: New object for AppBundle
            display: ~
            actions:
                save: ~
                list: ~
    edit:
        params:
            title: "You're editing the object \"%object%\"|{ %object%: Item.title }|"
            display: ~
            actions:
                save: ~
                list: ~
    show:
        params:
            title: "You're viewing the object \"%object%\"|{ %object%: Item.title }|"
            display: ~
            actions:
                list: ~
                new: ~
    actions:
        params:
            object_actions:
                delete: ~
            batch_actions:
                delete: ~
